name: Build Android

on:
  workflow_dispatch: # manually triggered

env:
  ANDROID_TARGET_SDK_VERSION: 27

jobs:
  build-android:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        target_arch: [arm, arm64, x86_64]

    runs-on: ${{ matrix.os }}
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install build utils
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Build
        run: |
          ./tools/android_build.sh $ANDROID_NDK_HOME $ANDROID_TARGET_SDK_VERSION $TARGET_ARCH
          rm -rf ./out_android/libnode

      - uses: actions/upload-artifact@v4
        with:
          name: node-android-${{ env.TARGET_ARCH }}
          path: out_android

  combine-android:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    needs: build-android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install build utils
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - uses: actions/download-artifact@v4
        with:
          pattern: node-android-*
          merge-multiple: true
          path: out_android

      - run: rm -rf out_android/libnode

      - name: Generate config.gypi
        run: ./configure

      - name: Combine
        run: |
          mkdir -p artifacts/bin
          mkdir -p artifacts/include
          cp -R out_android/* artifacts/bin
          ./tools/copy_libnode_headers.sh android
          cp -R out_android/libnode/include/* artifacts/include

      - uses: actions/upload-artifact@v4
        with:
          name: nodejs-mobile-android
          path: artifacts

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: node-android-*
